### PR TITLE
hit dice roll formula

### PR DESCRIPTION
**Pull request by f4hy**
WIP. Still testing.

Allows users to modify how hit dice are rolled. either normal, with advantage (take the highest of 2 rolls) or maximize the roll.

### CODE REVIEW

**Comment by roth-michael** [comment]
Anything left in this you wanna do? If not I can pull it and see about doing different HD rules depending on rest type

**Comment by f4hy** [comment]
Just tested that it works. So that I don't have translations for the other languages.

**Comment by roth-michael** [comment]
All good. Those are community-driven. Everything besides Brazilian Portuguese is probably horribly outdated.

**Comment by roth-michael** [comment]
FYI, most of the changes you'll see if you look at the latest commit are just preference things and fixing bugs I noticed in the existing code. The only thing I had to change in your PR was advantage; with the `r<3` from black blood, it'd have been `2d6khr<3` or something similar, which wouldn't process the reroll properly, so I moved the `kh` to the other side of the `r<3`. Thanks for your contribution!

**Pull request merged**
